version: '3'
services:
  
  client:
    build: ./client
    stdin_open: true
    ports:
      - 3000:3000
    volumes:
      - ./client:/app/client
    command: npm start  
    networks:
      - mern-app  
    
  api:
    build: ./api
    ports:
      - "5000:5000"
    command: npm start
    volumes:
      - ./api:/app/api
    networks:
      - mern-app
    depends_on:
      - mongo

  mongo:
    image: mongo:3.6.19-xenial
    ports:
      - "27017:27017"
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db

networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local